### ISSUE TITLE
(P4) On my phone I can’t log-in with metamask

### ISSUE THREAD

**Issue by Jipperism** [Network-Goods/hypercerts-pilot#44]
If this is difficult to solve, we could add a sentence somewhere that it isn’t optimized for phone at this point.

**Comment by Jipperism** [comment]
@holkeb @reasn [did you try to connect using the in-app browser from Metamask?](https://metamask.zendesk.com/hc/en-us/articles/6356387482523-How-to-use-the-MetaMask-Mobile-Browser). Because that seems to work for me.

**Comment by holkeb** [comment]
Hi @Jipperism, yes that works fine, thanks
